### ISSUE TITLE
Custom payloads for quick replies

### ISSUE THREAD

**Issue by NikV** [Botmock/botmock-dialogflow-export#35] opened 2019-08-13 18:59 UTC
**Overview**
In certain platforms, Dialogflow has limits around number of quick replies in an intent. Flows can silently exceed these limits. One potential work around is to leverage custom payloads in these cases.

**To Reproduce**

**Expected behavior**
Quick replies should not interrupt the flow

**Screenshots**
N/A

**Comment by nonnontrivial** [comment] 2019-08-13 19:29
This should be addressed by https://github.com/Botmock/botmock-dialogflow-export/pull/32

**Comment by reyerm** [comment] 2019-08-14 10:04
To me the issue is a bit broader, as Quick Replies in Dialogflow (weirdly) only allow one response per quick reply (even though more than one can work when imported like is happening from Botmock). To me i wonder if better solution isnt to use the Custom Payload to manage quickreplies, rather than via DF quickreply functionality? 
that said, design choice is naturally up to you to make best call.

**Closed** 2020-03-26 15:14 UTC
Labels: enhancement
